backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow
site_url: https://www.wargabantuwarga.com
display_url: https://www.wargabantuwarga.com

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Configuration"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "Site name"
            name: "site_name"
            widget: "string"
            hint: "The main name of the website, e.g., **Warga Bantu Warga** | Informasi Faskes & Alkes untuk COVID-19"
          - label: "Site tagline"
            name: "site_tagline"
            widget: "string"
            hint: "The tagline to accompany the name, e.g., Warga Bantu Warga | **Informasi Faskes & Alkes untuk COVID-19**"
          - label: "Site description"
            name: "site_description"
            widget: "string"
            hint: "The description of the site to be shown in the URL previews on Google, Facebook, Twitter, WhatsApp, etc."
  - name: "home_page"
    label: "Home Page"
    delete: false
    preview_path: home-page
    files:
      - name: "home_page"
        label: "Home Page"
        file: "_content/home-page.md"
        fields:
          - { label: "Title", name: "title", widget: "string", hint: "Page title" }
          - { label: "Body", name: "body", widget: "markdown", hint: "Page body" }
