name: Web Perf Check for Pull Request

on:
  #pull_request:
  pull_request_target:
    types: [labeled]

jobs:
  lhci:
    name: Run Lighthouse CI againts Pull Request
    runs-on: ubuntu-latest

    if: ${{ github.event.label.name == 'need-perf-check' }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: "wargabantuwarga"

      - name: "Lighthouse CI assertion"
        id: lhci
        shell: bash
        run: |
          yarn global add @lhci/cli@0.8.x
          echo -e "\n"
          echo "Start collecting LH report..."
          lhci collect --url=${{ steps.netlify.outputs.url }} --url=${{ steps.netlify.outputs.url }}/tentang-kami --url=${{ steps.netlify.outputs.url }}/donasi --url=${{ steps.netlify.outputs.url }}/faq --url=${{ steps.netlify.outputs.url }}/provinces -n=1
          echo -e "\n"
          echo "Start asserting LH score..."
          lhci assert --config=./lighthouserc.js
          echo -e "\n"
          echo "Start uploading the report..."
          lhci upload --target "temporary-public-storage" --githubAppToken "$LHCI_GITHUB_APP_TOKEN" --githubToken "$GITHUB_TOKEN"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
